# Generated by Django 5.2 on 2025-08-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminfo',
            options={'verbose_name': 'Информация о товаре', 'verbose_name_plural': 'Информация о товарах'},
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='value_info',
            field=models.CharField(default='Не указано', max_length=300, verbose_name='Значение информации'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='shop_api.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='type_info',
            field=models.CharField(max_length=150, verbose_name='Тип информации'),
        ),
    ]
